---
version: 2
project_name: gohl-api

checksum:
  disable: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: danielvollbro
    name: gohl-api
  draft: false
  prerelease: auto